### ISSUE TITLE
2 Rules having same name

### ISSUE THREAD

**Issue by sarvesh** [j-easy/easy-rules#106]
If two rules are having same name. Than the rule is ignored.
I used annotations.

**Comment by jokke150** [comment]
That is expected behavior.

[FAQs - 3. I've registered multiple instances of the same rule with different inputs, but it seems only the first instance is registered. What's happening?](https://github.com/j-easy/easy-rules/wiki/faqs#3-ive-registered-multiple-instances-of-the-same-rule-with-different-inputs-but-it-seems-only-the-first-instance-is-registered-whats-happening)

**Comment by benas** [comment]
@jokke150 Thank you for your reply!

@sarvesh Rules in easy rules must have a unique name within a rule set (`Rules` instance). That why you can't register two rules with the same name. If you use annotations, make sure to give your rule a name, or else it will be the class name by default.

If this answers your question, please close the issue.

Kr
Mahmoud
