### ISSUE TITLE
Shouldn't Priority annotation be absorbed by Rule annotation?

### ISSUE THREAD

**Issue by 3amprogrammer** [j-easy/easy-rules#127]
As far as I know `getPriority` is a kind of method that always returns some constant. Maybe it makes sense to move this configuration to Rule annotation next to description and name?

I have made this decision while porting this engine to PHP but it's not even in beta yet, so let me know what you think :)

**Comment by benas** [comment]
Hi,

If you put the priority as an attribute of the `@Rule` annotation, you cannot change it without recompiling the code:

```
@Rule (name = "myRule", description = "my Rule Description", priority = 3)
class MyRule { ... }
```

However, if you have a method annotated with `@Priority`, you can make it load the priority from an external resource and hence, you can change rules priorities without recompiling the code:

```
@Rule (name = "myRule", description = "my Rule Description", priority = 3)
class MyRule {

   @Priority
   public int getPriority() {
      return (int) ResourceBundle.getBundle("myRule.properties").getObject("priority");
   }

}
```

Does this make sense?

Kr
Mahmoud

**Comment by 3amprogrammer** [comment]
Yes, that helps. I haven't thought of recompiling, because in PHP we don't have such problems. I will keep your design However, because it makes perfect sense to load priority from an external resource. Thanks.

**Comment by benas** [comment]
Hi,

Just for your information, I added the ability to define the priority in the `@Rule` annotation coupled with the possibility to override (dynamically) if required with a method annotated with `@Priority` (see #96).

I just wanted to ask, do you want to have your work appear in the list [here](https://github.com/j-easy/easy-rules#easy-rules-in-other-languages) (even if it's a WIP)? If yes, you are welcome to open a PR, otherwise, if you give me your permission to reference it, I will do it.

Kr,
Mahmoud
