### ISSUE TITLE
Handle null values in Fact

### ISSUE THREAD

**Issue by ruchichhabra009** [j-easy/easy-rules#151]
Hi,
I am starting using it. I was previously using rulebook engine, but then got some blockers and moving to this. Is there any way to handle null values in fact, I do not want to receive null pointer exception. it should simply say rule failed.

**Comment by ruchichhabra009** [comment]
@benas 
I got the answer read the previous issues. Seems like the only way is to customize the listener to look for the exception.

**Comment by benas** [comment]
Can you please provide an example? That would help in understanding your use case. Thanks upfront.

**Comment by benas** [comment]
Any update on this?

**Comment by benas** [comment]
> it should simply say rule failed.

Easy Rules does not interpret user data, otherwise that would be a design mistake IMO. It is up to you to make sure no `null` values are passed as facts or make your rule implementation check for fact nullity. Here is an example:

```java
@Test
public void tetNullFact() throws Exception {
    // Given
    @Rule
    class MyRule {

        private boolean isExecuted;

        @Condition
        public boolean condition(@Fact("name") String name) {
            return name != null;
        }

        @Action
        public void action(@Fact("name") String name) {
            System.out.println("Hello " + name);
            isExecuted = true;
        }

        public boolean isExecuted() {
            return isExecuted;
        }
    }

    Facts facts = new Facts();
    facts.put("name", null);
    MyRule rule = new MyRule();
    Rules rules = new Rules(rule);
    RulesEngine rulesEngine = new DefaultRulesEngine();

    // When
    rulesEngine.fire(rules, facts);

    // Then
    assertThat(rule.isExecuted()).isFalse();
}
```

In this example, the rule should be executed (print "Hello" + name) only of the fact `name` is present. 
The example prints:

```
[main] DEBUG org.jeasy.rules.core.DefaultRulesEngineListener - Engine parameters { skipOnFirstAppliedRule = false, skipOnFirstNonTriggeredRule = false, skipOnFirstFailedRule = false, priorityThreshold = 2147483647 }
[main] DEBUG org.jeasy.rules.core.DefaultRulesEngineListener - Registered rules:
[main] DEBUG org.jeasy.rules.core.DefaultRulesEngineListener - Rule { name = 'MyRule', description = 'when condition then action', priority = '2147483646'}
[main] DEBUG org.jeasy.rules.core.DefaultRulesEngineListener - Known facts:
[main] DEBUG org.jeasy.rules.core.DefaultRulesEngineListener - Fact { name : null }
[main] DEBUG org.jeasy.rules.core.DefaultRulesEngineListener - Rules evaluation started
[main] DEBUG org.jeasy.rules.core.DefaultRuleListener - Rule 'MyRule' has been evaluated to false, it has not been executed
```

So even if the fact `name` is passed as null, the rule is still triggered (evaluated), but not executed.

You can find more details about the expected behaviour in [NullFactAnnotationParameterTest](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/test/java/org/jeasy/rules/core/NullFactAnnotationParameterTest.java).
