### ISSUE TITLE
Need to get expression result from action

### ISSUE THREAD

**Issue by wshandao** [j-easy/easy-rules#160]
Hi, As we business scenraio, we need to get expression result from action, so that we can continue to execute the logic, but the fire method is void type by default, how can I get expression result there?

The example as below
condition: courseUsedHour / courseTotalHour == 0.25
action：courseFee.budget - (refund.appliedCourseRefund + refund.courseRefund - refund.preAppliedCourseRefund) + fee.balance

actually I have defined three pojo like course, fee, refund to join the caculation, but no result returned

**Comment by benas** [comment]
Hi,

By design, rules do not return values. A rule action is not a function (that returns a value), it should be considered as an action that **have side effect**, for example, adding a new fact to the set of known facts which might drive the execution flow of subsequent rules.

Please find more details on the [FAQs](https://github.com/j-easy/easy-rules/wiki/faqs#2-i-would-like-to-return-a-value-upon-a-rule-execution-how-to-do-that).

Does this help?

Kr,
Mahmoud

**Comment by wshandao** [comment]
Okay, got it, thanks!
