### ISSUE TITLE
Set variables in conditions to use in actions

### ISSUE THREAD

**Issue by brunofrank** [j-easy/easy-rules#180]
Hey everyone,

In Drools we can set variables in conditions to use before, like that:

```
when
   user: user()
   user.age > 18
then
   user.setAsAccepted()
```

I know that I can do that passing into facts, but I think that it's not so hard to implement, and it will be very useful to create more dynamic rules.

I really appreciate if someone has an opinion about it.

**Comment by benas** [comment]
Any update on this?

**Comment by benas** [comment]
@brunofrank There is no current plan to add variables as I see no added value here. I'm closing this issue for now but feel free to add comments if necessary.

Thank you for opening this issue anyway!

**Comment by DrAyoub** [comment]
Hi @benas 
I am also facing the same problem. I try to use value of fact in actions
**Example :**
`[ {
        "name" : "high temperature alert",
        "description" : "The ambient temperature should always be maintained below 30 degree Celsius",
        "priority" : 2,
        "condition" : "value > 30",
        "actions" : [ "AddNotification(value);" ]
}]`

**Comment by benas** [comment]
@DrAyoub This is not a problem. Take a look at [this discussion](https://gitter.im/j-easy/easy-rules?at=5de024259319bb5190a95291) on gitter where you can find an example of how to do that.

**Comment by DrAyoub** [comment]
Thank you @benas  for your quick reply,
I have read the discussion. In discussion, I found `"facts.get('foo')"` which does not solve my problem. Because I am using kafka stream, I receive thousands of messages per second, each received message I take value from it and put it in facts, so if I use `"actions" : [ "AddNotification(facts.get('value'));" ]` maybe when the action executed take the value of the following message.
In my use case, I have to use the actual fact value that verified the condition.

**Comment by benas** [comment]
Well, that cannot happen since the call to the rules engine is blocking. If for each event you add the value to the facts then call the rules engine with these facts, then the listener will add/remove the fact immediately before/after rule executions (and this is a blocking call). So I see no way how facts can overlap.

That said, I don't know what is your experience with this (interesting!) use case, but IMO calling a **blocking** code (the rules engine in this case) for each event on a stream is not appropriate. I think a non-blocking reactive stream library is more appropriate (to handle back pressure, non blocking IO, etc).

**Comment by DrAyoub** [comment]
I think you are right. In case of blocking call, the facts can't overlap. I'm really confused between still working with easy-rules or search another alternative.
