### ISSUE TITLE
Question : what is the purpose of the support module

### ISSUE THREAD

**Issue by sarahBuisson** [j-easy/easy-rules#188]
Hello, I'm currently trying to do a kotlin version of your lib.
My question is , what is the purpose of the support module? Why have you put-it in a different module than the core?

Thank-you !

**Comment by benas** [comment]
> Hello, I'm currently trying to do a kotlin version of your lib.

That's awsome! I'm currently learning Kotlin (which is lovely BTW!) and I would be curious about your port of Easy Rules to Kotlin. Do you mind if I put a reference to it in the [readme](https://github.com/j-easy/easy-rules#easy-rules-in-other-languages) (even if it is a work in progress) ? I would love to help.

> My question is , what is the purpose of the support module? Why have you put-it in a different module than the core?

The reason for that module is to provide any support functionality that would not fit in the core module. For example, the [CompositeRule](https://github.com/j-easy/easy-rules/blob/master/easy-rules-support/src/main/java/org/jeasy/rules/support/CompositeRule.java) used to be in the core module as an implementation of the composite design pattern. However, creating a composite rule might differ from one use case to another: Would a composite rule apply all composing rules or the first rule that applies, or something else? Please see [issue 122](https://github.com/j-easy/easy-rules/issues/122#issuecomment-352177775) for more details. Since we could not put all these variations in the core module, it was decided to move them in an external module (which is obviously optional).

**Comment by benas** [comment]
@sarahBuisson I hope I answered your question, I'm closing this issue for now. Please feel free to add comments here and let me know if you need help in your kotlin port!
