### ISSUE TITLE
Add registerXXXListener(s) methods to RuleEngine interface

### ISSUE THREAD

**Issue by elitacco** [j-easy/easy-rules#216]
Can register methods in AbstractRuleEngine be exposed in RuleEngine interface? Otherwise we are forced to cast to implementation in order to be able to register listeners.

**Comment by benas** [comment]
This makes sense. However it will be a breaking change, so let me plan this for v4.

**Comment by benas** [comment]
While working on this, I came to the conclusion that dealing with listeners is actually an implementation detail. A similar example of this design is the one found in Spring Batch: A [job](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/Job.java) can have a [listener](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/JobExecutionListener.java) that is triggered before/after the job. Registering listeners is not part of the contract (The `Job` interface), but delegated to the the implementation [`AbstractJob`](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/job/AbstractJob.java#L245) (The same thing is done for a step). So in order to register a listener, one needs to use the implementation.

So I believe the current design here is ok. There would be no need to downcast if the rules engine variable is declared with the implementation.

I'm closing this issue for now.
