### ISSUE TITLE
how can I get the rule's name ?

### ISSUE THREAD

**Issue by duanshanchong** [j-easy/easy-rules#240]
eg:
```
[
  {
    "name": "alert",
    "description": "when temperature >=60, alert! ",
    "priority": 1,
    "condition": "record.temperature1 >= 60 ",
    "actions": [
      "task.remoteControl()",
      "task.sendAlert(ruleName)" // I want use the rule's name
    ]
  }
]
```

**I want use the rule's name, what should I do ?  thanks!**

**Comment by MatiWalk** [comment]
The base `Rule` interface has a getter for the name, if you created the rule, then you can access the field

**Comment by benas** [comment]
Excellent question! This is currently not possible because conditions and actions are not aware of the rule that encloses them.

I implemented this feature here: [rule_aware_condition_action.patch.txt](https://github.com/j-easy/easy-rules/files/3877046/rule_aware_condition_action.patch.txt)
It makes conditions/actions aware of the rule they belong to and adds them as a fact under the `self` key (`this` is a reserved keyword in both MVEL and SpEL) . With this patch, you can write something like:

```json
[
  {
    "name": "alert",
    "description": "when temperature >=60, alert! ",
    "priority": 1,
    "condition": "record.temperature1 >= 60 ",
    "actions": [
      "task.remoteControl()",
      "task.sendAlert(self.rule.name)"
    ]
  }
]
```

`self` refers to the current action (or condition if used in a condition) and allows you to get the enclosing rule and its name.

What do you think?

**Comment by benas** [comment]
This is possible using a rule listener. Here is a quick example, given the following `alert-rule.json` file:

```json
[
  {
    "name": "alert",
    "description": "send alert",
    "condition": "true",
    "actions": [
      "System.out.println(rule.name);"
    ]
  }
]
```

you can add the rule as a fact using the listener:

```java
MVELRuleFactory mvelRuleFactory = new MVELRuleFactory(new JsonRuleDefinitionReader());
Rules myRules = mvelRuleFactory.createRules(new FileReader("src/test/resources/alert-rule.json"));
DefaultRulesEngine rulesEngine = new DefaultRulesEngine();
rulesEngine.registerRuleListener(new RuleListener() {
    @Override
    public boolean beforeEvaluate(Rule rule, Facts facts) {
        return true;
    }

    @Override
    public void afterEvaluate(Rule rule, Facts facts, boolean evaluationResult) {
    }

    @Override
    public void beforeExecute(Rule rule, Facts facts) {
        facts.put("rule", rule);
    }

    @Override
    public void onSuccess(Rule rule, Facts facts) {
        facts.remove("rule");
    }

    @Override
    public void onFailure(Rule rule, Facts facts, Exception exception) {
        facts.remove("rule");
    }
});
Facts facts = new Facts();
rulesEngine.fire(myRules, facts);
```

This prints: `alert` which is the rule name.
