### ISSUE TITLE
Rules order

### ISSUE THREAD

**Issue by penbachi** [j-easy/easy-rules#269]
Hello, It will nice to have option to fire the rules in which they were registered. Or do we any option already available?

**Comment by benas** [comment]
You have two options:

1. set rule priorities based on their insertion order
2. Extend `Rules` and use a list to hold rules (instead of the `TreeSet` used by default in `Rules`)

For option 2, here is a quick example:

```java
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.jeasy.rules.core.RuleProxy;

public class MyRules extends Rules {

	private List<Rule> rules = new ArrayList<>();

	public void register(Object rule) {
		rules.add(RuleProxy.asRule(rule));
	}

	@Override
	public Iterator<Rule> iterator() {
		return rules.iterator();
	}

	@Override
	public boolean isEmpty() {
		return rules.isEmpty();
	}
}
```

then use it as follows:

```java
Rule rule1 = new MVELRule().priority(2).when("true").then("System.out.println(\"rule 1\");");
Rule rule2 = new MVELRule().priority(1).when("true").then("System.out.println(\"rule 2\");");
MyRules rules = new MyRules();
rules.register(rule1);
rules.register(rule2);

RulesEngine rulesEngine = new DefaultRulesEngine();
rulesEngine.fire(rules, new Facts());
```

this prints:

```
rule 1
rule 2
```

which means rules are executed in their insertion order and not according to their priorities (which is the default). If you use `Rules` instead of `MyRules`, the example prints:

```
rule 2
rule 1
```

which means rules are executed according to their natural order.

Hope this helps.
