### ISSUE TITLE
Does it support complex nested statements?

### ISSUE THREAD

**Issue by Atotomu** [j-easy/easy-rules#278]
Does it support complex nested expressions in yaml files？

**Comment by dvgaba** [comment]
Might be able to help if you can share a basic use case. We usually store all our rules in MongoDb as Json. We have some rules which uses for loop with nested ifs.

**Comment by benas** [comment]
I agree with @dvgaba , an example would help because I'm not sure I understand your requirement.

Regardless of the rule descriptor format (yaml or json), the condition is a `String`, so the expression can be as complex as you want. For actions, it is an array of `String`s, so same here you can add as many (complex) actions as you want.

I'm closing this issue for now, but you can add a comment if you need further help.
