### ISSUE TITLE
Why the value of Fact must be not null?

### ISSUE THREAD

**Issue by lanpf** [j-easy/easy-rules#294]
In some cases, i need to do actions if the value is null. And Null values have different meanings in different cases.
When I upgrade to 4.0.0，null value causes an exception. It means i can only stay in 3.x.

**Comment by benas** [comment]
If the fact is `null`, why would you put it in `Facts` in the first place?

**Comment by lanpf** [comment]
Because null is meaningful just like other fact for my cases.
In case A, null fact means lower priority, but higher priority in case B.
We need to adjust priorities dynamically when we deploy our application to different environment.

Case A:
---
name: "data"
description: data is null
condition: data == null
actions:
  - validationResult.priority = 1 

Case B:
---
name: "data"
description: data is null
condition: data == null
actions:
  - validationResult.priority = 5

**Comment by quaff** [comment]
@benas I think `null` fact is reasonable, can you add an option to allow `Facts` accept `null`?

**Comment by quaff** [comment]
Both SPEL and MVEL accepts null-valued identifier.

**Comment by benas** [comment]
> Because null is meaningful just like other fact for my cases.

@lanpf  

1. This "meaning" can be expressed in a higher level expression like "data is absent or present" instead of the low level "data == null". So instead of putting a `null` fact (or an eventually `null` fact), you can check if the data is `null` and add a boolean fact to signal the absence of that data:

```diff
-facts.put("data", data); // data might be null
-condition: data == null
+if (data == null) {facts.put("dataIsAbsent", true)}
+condition: dataIsAbsent == true
```

You can think of this like the `Optional` type in Java 8: Instead of writing `if (data != null) { .. }`, one would write something like `if (optionalData.isPresent()) { .. }`. Same thing with `data == null` and `dataIsAbsent == true`, they both express the same thing yet the latter is more expressive than the former (and more safe as well, as explained in the next point).

2. Moreover, if `data` is used in the action when it is `null`, you can get `NullPointerException`s at runtime, something like:

```yaml
name: "data"
description: data is null
condition: data == null
actions:
  - data.x = 1
```

Of course, it's obvious here to find the mistake by just looking at the rule, but when you have a lot of variables involved, it might not be so obvious and you are not safe against NPE at runtime. As you might already know, the `null` reference has been qualified as a [billion-dollar mistake](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions) by its creator, and the fact that Easy Rules v4 does not allow `null` facts will (hopefully) prevent you from making this mistake.

Do you agree?

>  I think null fact is reasonable, can you add an option to allow Facts accept null? Both SPEL and MVEL accept null-valued identifier.

@quaff  No, there is no plan to add such option because it would be confusing. SpEL and MVEL are low level expression languages to manipulate variables, `nulls`, etc. Easy Rules on the other hand is at a higher level of abstraction that has a null-safe type-safe domain concept called `Fact` (#276 ) and in which rules are intended to be expressed in business terms. In my experience (and I think most people would agree with this), non-technical business people won't express business rules by saying `when X is null` or `when Y is nil`, they will say `when X is unavailable` or `when Y is provided` or something similar instead. Hence, I believe it is a good practice to express rules in a way that is as close as possible to the way that non-technical business people would use to define them.

Type safety and null safety were two of the most important themes of v4, and I believe this enforces good practices of writing rules in high level business terms instead of low level programming constructs.

**Comment by quaff** [comment]
@benas I agree.

**Comment by lanpf** [comment]
@benas I agree.  I will use higher level expression instead.

**Comment by jhsenjaliya** [comment]
> Easy Rules on the other hand is at a higher level of abstraction that has a null-safe type-safe domain concept called Fact

@fmbenhassine , while i agree with this statement, if easy rule wants to support SpEL and MVEL, it has to provide a way to define nullable values which SpEL and MVEL supports as a rule. The solution you have shown - to check for null explicitly, wont work because it needs another field to be used in rule compare to original name, which defeats the purpose.

> In my experience (and I think most people would agree with this), non-technical business people won't express business rules by saying `when X is null` or `when Y is nil`, they will say `when X is unavailable` or `when Y is provided` or something similar instead. Hence, I believe it is a good practice to express rules in a way that is as close as possible to the way that non-technical business people would use to define them.

actually i was surprised to see non technical folks using nulls and other basic checks all the time, because of the way data and table is defined. so seems like this is a common use-case.

so I think allowing null value ( may be even introducing new `nullable` Facts would be useful )

btw, Currently if someone needs this, the way i get this is by not even setting the field in Facts and let the expression execute without it ( yet to check if there is any side effect of this on result for complex rule )

Thanks!
