### ISSUE TITLE
V4.0.0 : Fact no longer filled with the action result

### ISSUE THREAD

**Issue by M3lkior** [j-easy/easy-rules#295]
Hi,

We are using Easy Rules V.3.4.0 in our project as a calculation engine. Here is the data set we are using to get result in Fact Map :

A rules.json defines our rules 
```
[
  {
    "name": "frais bancaire rule",
    "priority": 1,
    "condition": "true",
    "actions": [
      "FB_CALCULATED = (TX_FB / 100) * PRX_ACHAT"
    ]
  },
  {
    "name": "frais bancaire x2",
    "priority": 1,
    "condition": "FB_CALCULATED >= 5",
    "actions": [
      "FB_CALCULATED_X2 = FB_CALCULATED * 2"
    ]
  },
  {
    "name": "frais bancaire 3",
    "priority": 2,
    "condition": "true",
    "actions": [
      "FB_CALCULATED_3 = TX_FB * PRX_ACHAT"
    ]
  }
]
```
And the POC implementation code : 

```
   public static void main(String[] args) throws Exception {
        // define facts
        Facts facts = new Facts();
        facts.put("TX_FB", "2");
        facts.put("PRX_ACHAT", "156");
        RulesEngine rulesEngine = new DefaultRulesEngine();

        // define rules
        MVELRuleFactory ruleFactory = new MVELRuleFactory(new JsonRuleDefinitionReader());
        Rules fbRules = ruleFactory.createRules(new FileReader("src/main/resources/fraisBancaire.json"));

        rulesEngine.fire(fbRules, facts);
        System.out.println("JSON :");
        System.out.println(facts.get("FB_CALCULATED").toString());
        System.out.println(facts.get("FB_CALCULATED_X2").toString());
}
```

In v3.4.0, Easy Rules automatically filled the Fact map with the operation result  (i.e. `FB_CALCULATED` , `FB_CALCULATED_X2` or `FB_CALCULATED_3`) during fired which cover our need to evaluate mathematical operation and use calculated result in other action.

Since v4.0.0 and Fact object introduction, this feature is gone.

Would you plan to be iso-functionnal in this 4.0.0 ? We want to migrate but we need this feature for that ... 

Thanks for you reply

**Comment by benas** [comment]
Hi @M3lkior ,

Thank you for opening this issue. In your first rule here:

```json
{
    "name": "frais bancaire rule",
    "priority": 1,
    "condition": "true",
    "actions": [
      "FB_CALCULATED = (TX_FB / 100) * PRX_ACHAT"
    ]
  }
```

What is the type of `FB_CALCULATED `?

> Fact no longer filled with the action result

You are expecting the result of the action to be filled in as a fact, but what type should Easy Rules use for that fact?

If I want to get the fact after firing the rule, which type should I use for that? Since I don't know the type, I tried the following but it fails with a `ClassCastException`:

```java
public static void main(String[] args) { // using v3.4.0
        MVELRule rule = new MVELRule()
                .name("frais bancaire rule")
                .priority(1)
                .when("true")
                .then("FB_CALCULATED = (TX_FB / 100) * PRX_ACHAT");
        Rules rules = new Rules();
        rules.register(rule);
        Facts facts = new Facts();
        facts.put("TX_FB", "2");
        facts.put("PRX_ACHAT", "156");
        RulesEngine rulesEngine = new DefaultRulesEngine();
        rulesEngine.fire(rules, facts);
        short FB_CALCULATED = facts.get("FB_CALCULATED"); // I don't know the type of FB_CALCULATED, so let me try "short" ...
        System.out.println("FB_CALCULATED = " + FB_CALCULATED);
        // fails with: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Short
    }
```

How would you infer the type of `FB_CALCULATED` from the expression `FB_CALCULATED = (TX_FB / 100) * PRX_ACHAT`?

**Comment by benas** [comment]
@M3lkior Any update on this?

**Comment by M3lkior** [comment]
Hi @benas ,

Sorry for de delay

For test purpose, you can find my POC project here, illustrate the use case described below : https://github.com/M3lkior/poc-easy-rules
the `master` branch is about v3 and a `test/v4` branch is about Easy rules v4. Just run the `Main` class to see the working result on v3

When i tried Easy-rules, I was just surprised to see that he was able to perform the calculation of the operation and add this result as `String`, containing a `Double` result.

So to answer i imagine that you have to push the result in String or test that this String is a numeric by using `Apache Commons lang's isNumber()` method for example

Today with v3, we cast the String result to a Double type and it works like a charm !

NB : In our real project, we are using the MVELFactory to created rules from a json (mongo stored) structure :   

```java

    /**
     * Create an easy-rule {@link Rule} from {@link CostComponentEntity} content
     *
     * @param cc           a {@link CostComponentEntity} containing formula and parameters
     * @param formulaValue the applicable {@link FormulaValueEntity}
     * @return a {@link Rule} matching {@link CostComponentEntity} and {@link FormulaValueEntity} content
     */
    protected static Rule createRuleFromCostComponent(CostComponentEntity cc, FormulaValueEntity formulaValue) {
        return new RuleBuilder()
            //name is discreet for composite rules
            .name(cc.getCode() + "[" + formulaValue.hashCode() + "]")
            .description(cc.getDescription())
            .priority(1)
            .when(new MVELCondition(formulaValue.getCondition())) // example :  FACT_1 > 10
            .then(new MVELAction(String.format(FORMULA_PATTERN, cc.getCode(), formulaValue.getFormula()))) // example FB_CALCULATED = (TX_FB / 100) * PRX_ACHAT
            .build();
    }
```

**Comment by benas** [comment]
Thanks for the update. This is where I wanted to come.

> So to answer i imagine that you have to push the result in String or test that this String is a numeric by using Apache Commons lang's isNumber() method for example

That's exactly what we should **not** do: testing if the type is numeric and try to cast it. This is not type safe and can lead to all kinds of type conversion issues. I explained these problems in details in https://github.com/j-easy/easy-rules/issues/280#issuecomment-632925046 (which is a duplicate issue BTW). What we should be doing instead is putting a *typed* fact in Facts (so that we know the type upfront) and use it in EL expressions.

> Today with v3, we cast the String result to a Double type

I still don't see how you decided to use `Double` and not `Float` or `BigDecimal` here. If we want Easy Rules to add facts dynamically, we need to find a way to tell it how to infer the type from the expression.

One of the motivations of adding the Fact API is type safety. Since v4, facts cannot be assigned dynamically because Easy Rules cannot infer the type from the expression. Facts cannot be re-assigned neither (because one might change the type of a fact in a subsequent rule), so you can think of them as final variables. However, they can be mutable. What you can do is encapsulate your variables in a wrapper data class, something like:

```java
public class Data {
    private Double FB_CALCULATED;
    private int TX_FB;
    private int PRX_ACHAT;
    // getters + setters

   // /!\ Note how all types are known upfront
}
```

Then put an instance of this class as a fact:

```java
Facts facts = new Facts();
Data data = new Data();
data.set TX_FB(30);
facts.put("data", data); // or facts.put("d", data); to type less characters in your EL expressions
```

and use it in your rule:

```json
{
    "name": "frais bancaire rule",
    "priority": 1,
    "condition": "true",
    "actions": [
      "data.FB_CALCULATED = (data.TX_FB / 100) * data.PRX_ACHAT"
    ]
  }
```

Null safety (https://github.com/j-easy/easy-rules/issues/294) and type safety (#276) were the two most significant features requested by users, and it was not possible to introduce them in the v3 line due to breaking changes. I understand this is a breaking change, that's why I introduced it only in v4, but it makes Easy Rules safer and more secure.

It should not be surprising that migrating to a major version might introduce some work. In this case, the work consists in encapsulating variables in a holder class and adding a prefix like `d.` in your expressions as shown previously. This shouldn't be a big deal and would give you the same result as v3. You can find a migration guide [here](https://github.com/j-easy/easy-rules/releases/tag/easy-rules-4.0.0), and if you need support in your migration I would love to help!

I'm closing this issue for now, but let me know if you need further support. Thank you.

**Comment by M3lkior** [comment]
Hi @benas , thanks for the support and the explanations.

Unfortunately it will be difficult to use a class to WRAP Data because we can not know in advance the content of an action (maybe we can generate class on the fly to achieve that)

for now we can stay in v3 but i will study this refactoring

Thanks

**Comment by benas** [comment]
> Unfortunately it will be difficult to use a class to WRAP Data because we can not know in advance the content of an action 

I'm not sure I understand this. If you don't know  the content of an action in advance, how would you write an EL expression for it (be it in v3 or v4)?

**Comment by M3lkior** [comment]
We create rules from API calls. Rule's action are, in our use case, an arithmetic formula which contains known parameters (like `PRX_ACHAT `) by the API
