### ISSUE TITLE
Add example / tutorial for SpelRule.

### ISSUE THREAD

**Issue by hiteshyantriks** [j-easy/easy-rules#304]
There is not tutorial to learn and understand the SpelRule.

**Comment by benas** [comment]
The tutorial you are looking for is the same as the [shop tutorial](https://github.com/j-easy/easy-rules/wiki/shop) except using `SpELRule/SpELRuleFactory` instead of `MVELRule/MVELRuleFactory`. If you are talking about the syntax, you can refer to the reference documentation of SpEL or take a look at the tests of the [spel module](https://github.com/j-easy/easy-rules/blob/master/easy-rules-spel/src/test/java/org/jeasy/rules/spel).
