### ISSUE TITLE
override `public String getName()` not making rule name unique

### ISSUE THREAD

**Issue by samyc1201** [j-easy/easy-rules#312]
Due to some reason, I prefer not to use reflection, so based on this [wiki](https://github.com/j-easy/easy-rules/wiki/defining-rules), I sticked to the first way like below:

```
public interface Rule {

    /**
    * This method encapsulates the rule's conditions.
    * @return true if the rule should be applied given the provided facts, false otherwise
    */
    boolean evaluate(Facts facts);

    /**
    * This method encapsulates the rule's actions.
    * @throws Exception if an error occurs during actions performing
    */
    void execute(Facts facts) throws Exception;

    //Getters and setters for rule name, description and priority omitted.

}
```

My rule extends `Rule` interface, and to make the rule name unique, I override the method as below:

```
public String getName() {
	return "Gender eligibility rule";
}
```

I have multiple similar rules, while I try to register them, only first rule is taken. 

After I change to annotation way `@Rule(name = "gender rule", description = "my rule description")`, it is working fine.

I see the comment mention:

`//Getters and setters for rule name, description and priority omitted.`

I check the source `Rule.java`, there is no setter inside, what is the correct way to override the default rule name? Or it is a bug while rule engine only read the name from annotation?

**Comment by benas** [comment]
> Due to some reason, I prefer not to use reflection

Easy Rules creates dynamic proxies for annotated objects. JDK dynamic proxies have indeed a small overhead, but this is not significant in most cases (a SO thread on the matter can be found [here](https://stackoverflow.com/questions/1856242/performance-cost-of-java-dynamic-proxy) with some good references). We also made some improvements to cache reflective access (see #221) which improved the overall performance. Obviously, nothing would equal the performance of a non-proxied version, but I just wanted to mention that here.

> I have multiple similar rules, while I try to register them, only first rule is taken.

A `Rules` instance represents a namespace for rules, meaning rules must have a unique names within a given namespace. So you need to make sure each rule has a different name (This is explained in the [FAQ](https://github.com/j-easy/easy-rules/wiki/faqs#3-ive-registered-multiple-instances-of-the-same-rule-with-different-inputs-but-it-seems-only-the-first-instance-is-registered-whats-happening)).

By default, there is no way to override the rule's name after it was set at creation time (at least this is the case for `BasicRule` and proxies created from annotated objects). This is because the rule's name is used in `equals`/`hashcode`/`compareTo` methods which may lead to unintended side effects if changed afterwards. That said, you can always add a setter to your rule's implementation if you really need to change it afterwards and are aware of the potential side effects.

I'm closing this issue for now, but feel free to add a comment if you need further support on this.
