### ISSUE TITLE
Can i have an action that stops further rule execution?

### ISSUE THREAD

**Issue by ilusha1991** [j-easy/easy-rules#315]
Use case: 
I use yamel with multiple conditions 
I have bunch of rules that are "terminal", i.e. no further rules should be executed after them. 
I have some rules which are non terminal, and should allow further rule evaluation, regardless if they have been evaluated true or false.  

possible solution: 
I can have conditions like: "originalCondition == true && continueEvaluation == true"
but that is very verbose, is there any way to trigger the end of execution from an action?

**Comment by ilusha1991** [comment]
I did end up coming up with a more elegant solution:
After getting my mvel rules from the factory, i wrapped each one in a wrapper rule
which addsa condition evaluating if it should stop execution.

RuleBuilder()
                                .name(r.getName())
                                .description(r.getDescription())
                                .priority(r.getPriority())
                                .when(fa -> !(boolean)fa.get("stop") && r.evaluate(fa))
                                .then(r::execute)
                                .build()

this approach flushed out a bug, as i was trying to have mvel action to add a fact. 
I resorted to adding my facts collection as a fact to itself, so it can be referenced  from mvel.
when running, a stack overflow is caused by the toString function.
workaround is to wrap the facts in another object.
did i miss a built in way to add a fact to the facts in mvel? please let me know.

**Comment by benas** [comment]
It is not possible to add a fact from an EL expression because EL expressions are written in MVEL/SpEL which are dynamically typed languages, while `Fact` is a Java API and hence statically typed (since v4, see #276). So Easy Rules cannot know which type it should use for the added fact. See #280 and #295 for more details.

Your second approach is the way to go for your use case: using a flag to signal that the execution should stop and change this flag from any rule when appropriate.
