### ISSUE TITLE
Why all j-easy projects are in maintenance mode ?

### ISSUE THREAD

**Issue by M3lkior** [j-easy/easy-rules#331]
Hello j-easy team ! I see that easy-rules status has changed to maintenance mode since December 2020 and other j-easy projects (like `easy-flow`) are archived. In the project description, you don't give us information about the maintenance mode reasons. We are using those projects in my organization and i need to know if we can migrate to another solution (`easy-flow` / `easy-rules`)

Sorry to learn that those projects are not maintained anymore ...

**Comment by benas** [comment]
Easy Rules, Easy Batch and Easy Random are still maintained and I have no plans to abandon them. Maintenance mode, as explained in their readme, means only bug fixes will be addressed, but no new features will be added. As of v4.1, I consider Easy Rules as feature complete. Any new expression language support or engine implementation can be developed as an extension, but the core APIs are considered stable now. These projects are used in production by several organisations and they will be maintained as long as my free time permits with the help of the awesome little community around them.

The other projects from the portfolio did not get the same traction, certainly because they did not get the love they deserve due to my lack of time. So the reason is that I don't have time and energy to maintain 7 projects. This has been overwhelming over the years and became harmful to my mental health. That's why I decided to archive them. Archiving them does not mean they are bad or poorly designed, this was done for the sole reason that I could not cope with the load of feature requests, support requests, etc. I know there are sponsorship programs for OSS, but I never asked for money and I will never do it. I'm just not interested in getting paid to work on these projects. When I created this j-easy organization, my goal was to increase the bus factor on these projects, which is currently equal to 1 .. so if someone is interested in taking the lead on one of these projects, I'm open to hand them over.

> you don't give us information about the maintenance mode reasons

Now that I gave you the reason, I think you should not be looking for a reason. If you (or your organisation) decided to include an open source project in your toolchain, you (or your organisation) have implicitly accepted the risk that this project might be abandoned in the future, for whatever reason. Fortunately, j-easy projects are released under the terms of the permissive MIT license, so feel free to fork the project you need and use it and maintain it as you like, as long as the license is respected. OSS FTW!

I'm closing this issue for now, but don't hesitate to add a comment if you still have other questions/concerns. You can also reach out to me directly if needed.
