### ISSUE TITLE
Add no-args version of 'fire' to 'DefaultRulesEngine'

### ISSUE THREAD

**Issue by will-gilbert** [j-easy/easy-rules#84]
After the rules and facts have been submitted to the rules engine via ```fire(rules,facts)```, if a fact is updated or added, or a rule is added or removed,  the engine needs to reevaluate these facts/rules. In this case, a no-args ```fire``` method could be invoked without having to provide references to the rules and facts instances previously submitted.

Alternatively, some sort of ```revaluate```, ```factsUpdated``` or ```rulesUpdated``` could be used.

This is a **syntactic sugar feature** and has low or no priority.

**Comment by benas** [comment]
> After the rules and facts have been submitted to the rules engine via fire(rules,facts), if a fact is updated or added, or a rule is added or removed, the engine needs to reevaluate these facts/rules.

This is exactly what a forward chaining inference engine would do. It continuously re-evaluate rules on facts until no more rules can be fired.

Currently, there is only one implementation of the `RulesEngine` interface which is `DefaultRulesEngine`: a stupid engine that simply iterates on a set of ordered rules and evaluate/execute them in one shot and then it stops. It does not reevaluate rules on facts until there are no more rules to apply.

I'm planning to add other implementations like `ForwardChainingRulesEngine` and `BackwardChainingRulesEngine` in a future version.

That said, I think adding a method `fire()` to `DefaultRulesEngine` is by design out of scope. Do you see the point?

**Comment by will-gilbert** [comment]
Sure do.  And I like it!  Adding that method to 'Default' make perfect sense. Thanks, Man.

**Comment by zhhaojie** [comment]
that's how `InferenceRulesEngine` came out .
