### ISSUE TITLE
Set rule priorities at registration time

### ISSUE THREAD

**Issue by matthew-carroll** [j-easy/easy-rules#92]
My rules are not executed in the order I add them.  This requires that each rule be able to evaluate itself in isolation which requires more conditions per rule.  Also, this makes the "skip on first applied rule" pretty useless as far as I can tell.

**Comment by benas** [comment]
Hi,

> My rules are not executed in the order I add them

Rules are not executed in the order you add them. They are executed according to their natural order, which is their priorities by default. See here for more details: https://github.com/j-easy/easy-rules/wiki/defining-rules#rules-priorities

As mentioned in the wiki, you can change the natural order by implementing the `compareTo` method.

Does this help?

Kr
Mahmoud

**Comment by matthew-carroll** [comment]
Are you open to altering that behavior?  I think the most "natural order" would be the order the rules are added.  In my opinion, an individual rule should not have to know its order relative to other rules.  In fact, I would consider that a bug.  It's the client that assembles the rules that holds a global understanding about how the rules relate to each other.

In my case compareTo is no good because the individual rules can't know the other rules around them.  I can use @priority and pass in a priority, but that requires adding a parameter to the constructor of every rule.  Also, at the moment I'm getting a crash with @priority that I filed another issue for.

**Comment by benas** [comment]
> I think the most "natural order" would be the order the rules are added

A rule set is not ordered by definition, it is a set. Insertion order makes no sense here. That's why you have to define what "natural" order is.

> In my opinion, an individual rule should not have to know its order relative to other rules. In fact, I would consider that a bug. It's the client that assembles the rules that holds a global understanding about how the rules relate to each other.

This is the case currently, rules should not be aware of other rules or any execution order. For example, in the [shop](https://github.com/j-easy/easy-rules/wiki/shop) example, the age rule is not aware of the alcohol rule or if it will be fired before or after it. It is the client that gives them priorities to fire them in the desired order.

Do you agree?

**Comment by matthew-carroll** [comment]
I can definitely understand the desire in many situations to treat rules as a set.  So that should certainly be an option.  But isn't there an equal value in ordering?  And shouldn't that ordering be define-able at the point of the engine Object?

I'm currently using Easy Rules as a Chain of Responsibility.  I would imagine that such a use-case is common.  In those situations we'd like to go down an ordered list and exit upon first successful handling.  The ordering of rules create a filter effect whereby earlier rules can be more specific and later rules can be more general.  But the only way to do this without one rule understanding what another rule is doing is to have the configuration code set the order by leveraging this knowledge globally.  As I mentioned before, you can do this by making priority an input parameter to every Rule object.  This is what I've done so far.  But this practice is tedious, error prone, and it allows developers to add rules out of order which can lead to mistakes when other developers read that code.

Does that make sense?

**Comment by benas** [comment]
> shouldn't that ordering be define-able at the point of the engine Object?

You are right, it's better to decouple rule priority from the rule itself and set it at registration time.

> I'm currently using Easy Rules as a Chain of Responsibility. I would imagine that such a use-case is common. In those situations we'd like to go down an ordered list and exit upon first successful handling

Yes, I have a similar use case. The 'skipOnFirstAppliedRule' allows you stop the chain.

> Does that make sense?

This make sense and I agree with you. Rules priorities in Easy Rules are like rule salience in drools. I'm not sure there are people complaining about the salience being set on the rule itself.

Anyway, I see two options for now:

* Assigning rule priority in the rule set at registration time (no more priority parameter or method annotated with `@Priority` in rules). Something like:
```java
Rules rules = new Rules();
rules.register(rule1, 1); // second param is the priority
rules.register(rule2, 2);
```

* Setting priority using the requested DSL (see https://github.com/j-easy/easy-rules/issues/44#issuecomment-240414357).

Those are just ideas, please feel free to suggest any other way of achieving this!

Many thanks upfront!

PS: I changed the title of this issue to a more descriptive one of what we are trying to do.

**Comment by benas** [comment]
Hi,

> the only way to do this without one rule understanding what another rule is doing is to have the configuration code set the order by leveraging this knowledge globally. As I mentioned before, you can do this by making priority an input parameter to every Rule object. This is what I've done so far. But this practice is tedious, error prone, and it allows developers to add rules out of order which can lead to mistakes when other developers read that code

You don't need to pass an input parameter to every Rule object. The global knowledge can be externalised and accessed from `@Priority` methods to set the priority dynamically. For example, if you have a properties file with rule names associated with priorities:

```
rule1=5
rule2=15
```

The priority method can be something like:

```
@Priority
public int getPriority() {
   return (int) ResourceBundle.getBundle("rule-priorites.properties").getObject(getName());
}
```

This method can be put in a base class and inherited by multiple rules. Each rule can be tested in isolation (just ignoring the priority). The global knowledge (`rule-priorites.properties` file) can be changed without recompiling any code. I understand that if you want to do the same with a global map you need to pass the map to each rule object, but I would not do it that way (because you would recompile the code each time you change priorities).

So after re-reading this thread and evaluating the cost of change, I would stick with the priority defined at the rule's level just like the salience in drools.

Kr
Mahmoud
